environment {
    PATH = "$WORKSPACE/miniconda/bin:$PATH"
}

pipline {
    stages {
        stage('Setup miniconda') {
            steps {
                sh #!/usr/bin/env bash
                wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
                bash miniconda.sh -b -p $WORKSPACE/miniconda3
                hash -r
                conda config --set always_yes yes --set changeps1 no
                conda update -q conda
            }
        }
    }
}