version: "3.9"

services:
  http_server:
    image: nginx
    restart: always
    environment:
      - TZ=Asia/Yekaterinburg
    ports:
      - "80:80"
    volumes:
      - ./spa/dist/:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
    networks:
      app:
        ipv4_address: 192.168.1.100

    colorize_api:
      build:
        context: .
        dockerfile: ./api/Dockerfile
      networks:
        colorize_app:
          ipv4_address: 192.168.1.101

networks:
  app:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24