version: "3.9"

services:
  web:
    image: nginx
    restart: always
    environment:
      - TZ=Asia/Yekaterinburg
    ports:
      - "80:80"
    volumes:
      - ./spa/dist/:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
    networks:
      - custom

  app:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    ports:
      - "8000:8000"
    networks:
      - custom

networks:
  custom:
    driver: bridge